ElectronicsStore/Controllers/BackOfficeControllers/ArticleController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ElectronicsStore.Models;
using ElectronicsStore.Repositories;

namespace ElectronicsStore.Controllers
{
    public class ArticleController : Controller
    {
        private INewsRepository _newsRepository;
        private IPagerRepository _pagerRepository;

        public ArticleController(INewsRepository newsRepository, IPagerRepository pagerRepository)
        {
            _newsRepository = newsRepository;
            _pagerRepository = pagerRepository;
        }

        public IActionResult Articles(int page = 1)
        {
            NewsPager newsPager = new NewsPager();
            List<News> articles = _newsRepository.GetAllNews();

            newsPager = _pagerRepository.GetNewsPager(articles, page, 10);

            return View(newsPager);
        }

        public IActionResult AddArticle()
        {
            return View();
        }

        public IActionResult EditArticle(int id)
        {
            News article = _newsRepository.GetNews(id);
            return View(article);
        }
    }
}

ElectronicsStore/Controllers/FrontOfficeControllers/NewsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ElectronicsStore.Models;
using ElectronicsStore.Repositories;

namespace ElectronicsStore.Controllers
{
    public class NewsController : Controller
    {
        private INewsRepository _newsRepository;
        private IPagerRepository _pagerRepository;

        public NewsController(INewsRepository newsRepository, IPagerRepository pagerRepository)
        {
            _newsRepository = newsRepository;
            _pagerRepository = pagerRepository;
        }

        public IActionResult Index(int page = 1)
        {
            NewsView newsView = new NewsView();

            List<News> allArticles = _newsRepository.GetAllNews();
            List<News> recommendedArticles = _newsRepository.GetRecommendedNews();
            NewsPager newsPager = _pagerRepository.GetNewsPager(allArticles, page);

            newsView.NewsPager = newsPager;
            newsView.recommendedArticles = recommendedArticles;

            return View(newsView);
        }

        public IActionResult Article(int id)
        {
            News article = _newsRepository.GetNews(id);

            return View(article);
        }
    }
}

ElectronicsStore/Views/Partials/Admin/Articles/Articles/_ArticleList.cshtml
@model ElectronicsStore.Models.NewsPager

<div class="article-list-container assortment-card">
    <div class="list-header">
        <h4 class="assortment-heading text-nowrap">Lista artykułów</h4>
        @await Html.PartialAsync("/Views/Partials/Admin/_Pager.cshtml", Model.Pager)
    </div>
    <table class="table">
        <thead>
            <tr>
                <th class="th-rounded article-title-field">Tytuł</th>
                <th>Data publikacji</th>
                <th>Polecany</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.News.Count() > 0)
            {
                foreach (News news in Model.News)
                {
                    <tr class="list-row js-articleListItem" data-article-id="@news.NewsId">
                        <td class="list-name">
                            <div class="list-name-edit-container">
                                <a asp-controller="Article" asp-action="EditArticle" asp-route-id="@news.NewsId" class="list-name-edit">
                                    <div class="text-truncate">@news.Title</div>
                                    <img src="/icons/pencil.svg" class="list-name-edit--icon" alt="Edytuj" />
                                </a>
                                <a asp-controller="News" asp-action="Article" asp-route-id="@news.NewsId" class="list-name-edit-preview">
                                    <img src="/icons/eye-primary.svg" class="list-name-edit-preview--icon" alt="Pokaż" />
                                </a>
                            </div>
                        </td>
                        <td>@news.Date.Day.ToString("00") @news.Date.ToString("MMMM", CultureInfo.CreateSpecificCulture("pl")) @news.Date.Year</td>
                        <td>
                            <div class="form-check form-check--article-list form-switch">
                                @if (news.isRecommended)
                                {
                                    <input class="form-check-input js-articleIsRecommendedSwitch" checked type="checkbox" role="switch">
                                }
                                else
                                {
                                    <input class="form-check-input js-articleIsRecommendedSwitch" type="checkbox" role="switch">
                                }
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="list-row cursor-default">
                    <td class="list-name" colspan="3">
                        <span class="ps-2">Brak artykułów</span>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

ElectronicsStore/Views/Partials/Admin/Articles/Articles/_Toolbar.cshtml
<div class="toolbar-container">
    <div>
        <h3 class="toolbar-subtitle">Artykuły</h3>
        <h2 class="toolbar-title">Artykuły</h2>
    </div>
    <div class="toolbar-actions">
        <a asp-action="AddArticle" class="btn primary-btn">
            <img src="/icons/plus.svg" alt="Plus" />
            <span>Dodaj artykuł</span>
        </a>
    </div>
</div>