ElectronicsStore/Models/ViewModels/FrontOfficeViewModels/ProductCardView.cs
using System.Collections.Generic;

namespace ElectronicsStore.Models
{
    public class ProductCardView
    {
        public Category CurrentCategory { get; set; }
        public Product Product { get; set; }
        public List<ProductInformation> Informations { get; set; }
        public List<ProductInformation> Characteristics { get; set; }
        public List<Product> SimilarProducts { get; set; }
    }
}

ElectronicsStore/Controllers/FrontOfficeControllers/ProductCardController.cs
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using ElectronicsStore.Models;
using ElectronicsStore.Repositories;

namespace ElectronicsStore.Controllers
{
    public class ProductCardController : Controller
    {
        private ICategoryRepository _categoryRepository;
        private IProductRepository _productRepository;

        public ProductCardController(ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
        }

        public IActionResult Index(int id)
        {
            ProductCardView productCardView = new ProductCardView();

            Product product = _productRepository.GetProduct(id);
            Category currentCategory = _categoryRepository.GetCurrentCategory(product.CategoryId);
            List<ProductInformation> informations = JsonSerializer.Deserialize<List<ProductInformation>>(product.Information);
            List<ProductInformation> characteristics = product.Characteristics != null ? JsonSerializer.Deserialize<List<ProductInformation>>(product.Characteristics) : null;
            List<Product> similarProducts = _productRepository.GetSimilarProducts(product);


            productCardView.Product = product;
            productCardView.CurrentCategory = currentCategory;
            productCardView.Informations = informations;
            productCardView.Characteristics = characteristics;
            productCardView.SimilarProducts = similarProducts;

            return View(productCardView);
        }
    }
}

ElectronicsStore/Views/Partials/ProductCard/_Breadcrumb.cshtml
@model ElectronicsStore.Models.ProductCardView

<nav class="breadcrumb-container" aria-label="breadcrumb">
    <div class="breadcrumb">
        <a class="breadcrumb-item" asp-controller="Home" asp-action="Index">Strona główna</a>
        <a class="breadcrumb-item" asp-controller="Products" asp-action="Category" asp-route-id="">Kategorie</a>
        <a class="breadcrumb-item" asp-controller="Products" asp-action="Category" asp-route-id="@Model.CurrentCategory.CategoryId">
            @Model.CurrentCategory.Name
        </a>
    </div>
</nav>

ElectronicsStore/Views/Partials/ProductCard/_Description.cshtml
@model ElectronicsStore.Models.Product

<div class="card-container product-card-container product-card-description-container">
    <h3 class="product-card-heading">Opis produktu</h3>
    <div class="product-card-description-content">
        @Html.Raw(Model.Description)
    </div>
</div>

ElectronicsStore/Views/Partials/ProductCard/_FullscreenSlider.cshtml
@model ElectronicsStore.Models.Product

<div class="fullscreen-slider-container">
    <div class="fullscreen-slider-body">
        <div class="fullscreen-slider-header">
            <div class="fullscreen-slider-pagination"></div>
            <img src="~/icons/close.svg" alt="Close icon" class="fullscreen-slider-close" />
        </div>
        <div class="fullscreen-slider-content">
            <div class="swiper fullscreen-slider">
                <div class="swiper-wrapper">
                    @if (Model.Images.Count() != 0)
                    {
                        @foreach (ProductImage productImage in Model.Images)
                        {
                            <div class="swiper-slide d-flex align-items-center justify-content-center">
                                <img src="@Url.Content(productImage.Url)" alt="@productImage.Title" class="fullscreen-slide-image" />
                            </div>
                        }
                    }
                    else
                    {
                        <div class="swiper-slide d-flex align-items-center justify-content-center">
                            <img src="/images/no_photo.svg" alt="Brak zdjęcia" class="fullscreen-slide-image" />
                        </div>
                    }
                </div>
            </div>
            <div thumbsSlider="" class="swiper fullscreen-slider--thumbs">
                <div class="swiper-wrapper">
                    @if (Model.Images.Count() != 0)
                    {
                        @foreach (ProductImage productImage in Model.Images)
                        {
                            <div class="swiper-slide fullscreen-slide-thumb">
                                <img src="@Url.Content(productImage.Url)" alt="@productImage.Title" class="fullscreen-slide-thumb--image" />
                            </div>
                        }
                    }
                    else
                    {
                        <div class="swiper-slide fullscreen-slide-thumb">
                            <img src="/images/no_photo.svg" alt="Brak zdjęcia" class="fullscreen-slide-thumb--image" />
                        </div>
                    }
                </div>
            </div>
            <div class="fullscreen-slider-arrow fullscreen-slider-arrow-prev">
                <img src="~/icons/arrow-left-primary.svg" alt="Arrow left" />
            </div>
            <div class="fullscreen-slider-arrow fullscreen-slider-arrow-next">
                <img src="~/icons/arrow-right-primary.svg" alt="Arrow right" />
            </div>
        </div>
    </div>
</div>

ElectronicsStore/Views/Partials/ProductCard/_InformationAndPictures.cshtml
@model ElectronicsStore.Models.ProductCardView

<div class="card-container information-and-photos-container">
    <div class="tab-container">
        <div class="information-tab-container tab-container active">
            <div class="information-tab tab">
                <div class="tab-icon"></div>
                <span class="tab-name">Informacje</span>
            </div>
        </div>
        <div class="photos-tab-container tab-container inactive">
            <div class="photos-tab tab">
                <div class="tab-icon"></div>
                <span class="tab-name">Zdjęcia</span>
            </div>
        </div>
    </div>
    <div class="tab-content">
        <div class="tab-content-information">
            <div>
                <table class="tab-content-table">
                    <thead>
                        <tr>
                            <th colspan="2">Informacje podstawowe</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ProductInformation information in Model.Informations)
                        {
                            <tr>
                                <td>@information.Name</td>
                                <td>@information.Value</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @if (Model.Characteristics != null)
            {
                <div class="pt-4">
                    <table class="tab-content-table">
                        <thead>
                            <tr>
                                <th colspan="2">Cechy produktu</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (ProductInformation characteristic in Model.Characteristics)
                            {
                                <tr>
                                    <td>@characteristic.Name</td>
                                    <td>@characteristic.Value</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
        <div class="tab-content-photos d-none">
            @if (Model.Product.Images.Count() != 0)
            {
                @foreach (ProductImage productImage in Model.Product.Images)
                {
                    <div class="tab-content-photo">
                        <img src="@Url.Content(productImage.Url)" alt="@productImage.Title" class="product-card-slide-image" />
                        <div class="tab-content-action-buttons">
                            <div class="tab-content-photo-btn tab-content-photo-btn--zoom">
                                <img src="~/icons/search-plus.svg" alt="Zoom icon" />
                            </div>
                            <a href="@Url.Content(productImage.Url)" class="tab-content-photo-btn" download>
                                <img src="~/icons/download.svg" alt="Download icon" />
                            </a>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="tab-content-photo">
                    <img src="/images/no_photo.svg" alt="Brak zdjęcia" class="product-card-slide-image" />
                    <div class="tab-content-action-buttons">
                        <div class="tab-content-photo-btn tab-content-photo-btn--zoom">
                            <img src="~/icons/search-plus.svg" alt="Zoom icon" />
                        </div>
                        <a href="/images/no_photo.svg" class="tab-content-photo-btn" download>
                            <img src="~/icons/download.svg" alt="Download icon" />
                        </a>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

ElectronicsStore/Views/Partials/ProductCard/_Main.cshtml
@model ElectronicsStore.Models.Product

@{
    CultureInfo cultureInfo = new CultureInfo("pl-PL");
}

<div class="product-card-container card-container">
    <div class="product-card-main--images">
        <div class="swiper product-card-slider">
            <div class="swiper-wrapper">
                @if (Model.Images.Count() != 0)
                {
                    @foreach (ProductImage productImage in Model.Images)
                    {
                        <div class="swiper-slide d-flex align-items-center justify-content-center">
                            <img src="@Url.Content(productImage.Url)" alt="@productImage.Title" class="product-card-slide-image" />
                        </div>
                    }
                }
                else
                {
                    <div class="swiper-slide d-flex align-items-center justify-content-center">
                        <img src="/images/no_photo.svg" alt="Brak zdjęcia" class="product-card-slide-image" />
                    </div>
                }

            </div>
            <div class="product-card-slider-arrow-prev-container">
                <div class="product-card-slider-arrow-prev product-card-slider-arrow">
                    <img src="~/icons/arrow-left-primary.svg" alt="Arrow left" />
                </div>
            </div>
            <div class="product-card-slider-arrow-next-container">
                <div class="product-card-slider-arrow-next product-card-slider-arrow">
                    <img src="~/icons/arrow-right-primary.svg" alt="Arrow right" />
                </div>
            </div>
        </div>
        <div thumbsSlider="" class="swiper product-card-slider--thumbs">
            <div class="swiper-wrapper">
                @if (Model.Images.Count() != 0)
                {
                    @foreach (ProductImage productImage in Model.Images)
                    {
                        <div class="swiper-slide product-card-slide-thumb">
                            <img src="@Url.Content(productImage.Url)" alt="@productImage.Title" class="product-card-slide-thumb--image" />
                        </div>
                    }
                }
                else
                {
                    <div class="swiper-slide product-card-slide-thumb">
                        <img src="/images/no_photo.svg" alt="Brak zdjęcia" class="product-card-slide-thumb--image" />
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="product-card-main--info">
        <h3 class="product-card-name">@Model.Name</h3>
        <p class="product-card-code">@Model.Code</p>
        <div class="product-card-prices">
            @if (Model.OldPrice != null)
            {
                <div class="product-card-prices--old-price">
                    <span>@Model.OldPrice?.ToString("C", cultureInfo)</span>
                    <span>Netto/szt.</span>
                </div>
            }
            <div class="product-card-prices--current-price">
                <span>@Model.Price.ToString("C", cultureInfo)</span>
                <span>Netto/szt.</span>
            </div>
            <div class="product-card-availability-container">
                <div class="product-card-availability">
                    <div class="d-flex align-items-center">
                        @if (Model.Quantity >= 100)
                        {
                            <img src="~/icons/availability-big.svg" alt="Availibity big" class="availibity-icon" />
                            <span class="availability-status--big availability-status">Duża dostępność</span>
                        }
                        else if (Model.Quantity < 100 && Model.Quantity >= 50)
                        {
                            <img src="~/icons/availability-medium.svg" alt="Availibity medium" class="availibity-icon" />
                            <span class="availability-status--medium availability-status">Średnia dostępność</span>
                        }
                        else if (Model.Quantity > 0 && Model.Quantity < 50)
                        {
                            <img src="~/icons/availability-small.svg" alt="Availibity small" class="availibity-icon" />
                            <span class="availability-status--small availability-status">Mała dostępność</span>
                        }
                        else
                        {
                            <img src="~/icons/availability-no.svg" alt="Availibity no" class="availibity-icon" />
                            <span class="availability-status--no availability-status">Brak dostępności</span>
                        }
                    </div>
                    <div class="availability-quantity-status">
                        <img src="~/icons/quantity.svg" alt="Quantity" class="availibity-icon" />
                        <span class="quantity-status availability-status">@Model.Quantity szt.</span>
                    </div>
                    @if (Model.Quantity > 0)
                    {
                        <div class="add-to-cart-wrapper">
                            <div class="product-card-counter">
                                <span class="product-card-counter--button product-card-counter--decrement-button">-</span>
                                <input class="product-card-counter--input" type="number" value="1" min="1" max="@Model.Quantity" />
                                <span class="product-card-counter--button product-card-counter--increment-button">+</span>
                            </div>
                            <div class="btn primary-btn add-to-cart-button">
                                <img src="/icons/eye.svg" alt="Eye">
                                <span class="text-nowrap">Dodaj do koszyka</span>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ElectronicsStore/Views/Partials/ProductCard/_SimilarProducts.cshtml
@model List<ElectronicsStore.Models.Product>

@{
    CultureInfo cultureInfo = new CultureInfo("pl-PL");
}


<div class="card-container similar-product-container">
    <h3 class="product-card-heading">Podobne produkty</h3>
    <div class="swiper similar-products-slider">
        <div class="swiper-wrapper">
            @foreach (Product product in Model)
            {
                ProductImage mainProductImage = product.Images
                         .Where(image => image.IsMain == true)
                         .FirstOrDefault();

                <div class="swiper-slide similar-product-slide">
                    <a asp-controller="ProductCard" asp-action="Index" asp-route-id="@product.ProductId" class="similar-product-slide-content">
                        <div class="similar-product-img-wrapper">
                            @if (mainProductImage != null && mainProductImage.Url != null)
                            {
                                <img src="@Url.Content(mainProductImage.Url)" alt="@mainProductImage.Title" class="similar-product-img" />
                            }
                            else
                            {
                                <img src="/images/no_photo.svg" alt="Brak zdjęcia" class="similar-product-img" />
                            }

                            @if (product.SpecialOffer == SpecialOffer.Promotion)
                            {
                                <div class="badge promotion-badge">Promocja</div>
                            }
                            else if (product.SpecialOffer == SpecialOffer.New)
                            {
                                <div class="badge news-badge">Nowość</div>
                            }
                            else if (product.SpecialOffer == SpecialOffer.Outlet)
                            {
                                <div class="badge outlet-badge">Outlet</div>
                            }
                        </div>
                        <p class="similar-product-name">@product.Name</p>
                        <div class="similar-product-prices">
                            @if (product.OldPrice != null)
                            {
                                <div class="similar-product-prices--old-price">
                                    <span>@product.OldPrice?.ToString("C", cultureInfo)</span>
                                    <span>Netto/szt.</span>
                                </div>
                            }
                            <div class="similar-product-prices--price">
                                <span>@product.Price.ToString("C", cultureInfo) </span>
                                <span>Netto/szt.</span>
                            </div>
                        </div>
                        <div class="btn similar-product--see-btn">
                            <img src="~/icons/eye.svg" alt="Eye" />
                            <span>Zobacz produkt</span>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
    <div class="similar-products-slider-navigation">
        <div class="similar-products-arrow-prev similar-products-slider-arrow">
            <img src="~/icons/chevron-left.svg" alt="Chevron left" />
        </div>
        <div class="similar-products-arrow-next similar-products-slider-arrow">
            <img src="~/icons/chevron-right.svg" alt="Chevron right" />
        </div>
    </div>
</div>